web: coverage run ptero_petri/api/wsgi.py --port $PTERO_PETRI_PORT
orchestrator: coverage run ptero_petri/implementation/orchestrator/main.py
redis: redis-server --port $PTERO_PETRI_REDIS_PORT
rabbit: RABBITMQ_NODE_PORT=$PTERO_PETRI_AMQP_PORT RABBITMQ_NODENAME=ptero-petri-rabbitmq RABBITMQ_LOG_BASE=$PWD/var/log RABBITMQ_MNESIA_BASE=$PWD/var/rabbitmq-data rabbitmq-server
